import Head from "next/head";
import { ApolloClient, InMemoryCache } from "@apollo/client";
import { GET_ALL_POSTS, Post } from "../graphql/queries";
import Link from "next/link";

export const client = new ApolloClient({
    uri: "http://127.0.0.1:1337/graphql",
    cache: new InMemoryCache(),
});

type HomeProps = {
    posts: Post[]
}

export default function Home({ posts }: HomeProps) {
    return <div>
        <Head>
            <title>My blog</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href=""></link>
        </Head>
        <h1>Welcome to the CoderBlog</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse commodo non ex vel semper. Mauris sit amet dui non magna molestie pulvinar ac quis turpis. </p>
        <br />
        <h2>All posts</h2>
        <ul>
            {
                posts?.map((post) => <li key={post.attributes.title}>
                    <Link href={`/blog/${post.attributes.urlSlug}`}>
                        <h3>{post.attributes.title}</h3>
                        <p>{post.attributes.description}</p>
                    </Link>
                </li>)
            }
        </ul>
    </div>
}

export async function getStaticProps() {
    try {


        const { data } = await client.query({
            query: GET_ALL_POSTS
        })

        return {
            props: {
                posts: data.blogPosts.data
            }
        }
    } catch (error) {
        return {
            props: {
                posts: []
            }
        };
    }

}